[workspace]
members = ["projects/*"]
default-members = [
    "projects/wasmbind-katex",
    "projects/yew-katex",
    "projects/katex-preview",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
